/*
 * config.h - Library mode configuration for DOSBox-X headless builds.
 *
 * In full DOSBox-X, this is generated by autoconf. For the embeddable
 * library build, we provide the minimum set of types and feature flags
 * needed by the CPU core and supporting headers.
 */

#ifndef CONFIG_H_
#define CONFIG_H_

#include <cstdint>

/* Fundamental DOSBox types */
typedef intptr_t  Bits;
typedef uintptr_t Bitu;

/* Compiler-portable attributes */
#if defined(__GNUC__) || defined(__clang__)
#  define GCC_ATTRIBUTE(x) __attribute__(x)
#  define INLINE inline __attribute__((always_inline))
#elif defined(_MSC_VER)
#  define GCC_ATTRIBUTE(x)
#  define INLINE __forceinline
#else
#  define GCC_ATTRIBUTE(x)
#  define INLINE inline
#endif

/* Branch prediction hints */
#if defined(__GNUC__) || defined(__clang__)
#  define GCC_UNLIKELY(x) __builtin_expect((x), 0)
#  define GCC_LIKELY(x)   __builtin_expect((x), 1)
#else
#  define GCC_UNLIKELY(x) (x)
#  define GCC_LIKELY(x)   (x)
#endif

/* Feature flags for library mode.
 * These can be overridden via CMake target_compile_definitions. */
#ifndef C_FPU
#  define C_FPU 1
#endif
#ifndef C_DEBUG
#  define C_DEBUG 0
#endif
#ifndef C_HEAVY_DEBUG
#  define C_HEAVY_DEBUG 0
#endif
#ifndef C_DYNAMIC_X86
#  define C_DYNAMIC_X86 0
#endif
#ifndef C_DYNREC
#  define C_DYNREC 0
#endif

/* Features we explicitly disable in library mode */
#ifndef C_SDL2
#  define C_SDL2 0
#endif
#ifndef C_OPENGL
#  define C_OPENGL 0
#endif

/* Target CPU (x86 host) */
#ifndef C_TARGETCPU
#  if defined(__x86_64__) || defined(_M_X64)
#    define C_TARGETCPU X86_64
#  elif defined(__i386__) || defined(_M_IX86)
#    define C_TARGETCPU X86
#  else
#    define C_TARGETCPU X86_64
#  endif
#endif

/* Memory and paging */
#ifndef C_CORE_INLINE
#  define C_CORE_INLINE 1
#endif

/* Disable features not needed in library mode */
#ifndef C_EMSCRIPTEN
#  define C_EMSCRIPTEN 0
#endif

#endif /* CONFIG_H_ */
